CREATE TABLE passenger (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name       VARCHAR(100) NOT NULL,
    last_name        VARCHAR(100) NOT NULL,
    email            VARCHAR(255) NOT NULL,
    passport_number  VARCHAR(20)  NOT NULL,
    date_of_birth    DATE
);
CREATE UNIQUE INDEX ux_passenger_email ON passenger (lower(email));

CREATE TABLE booking (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    booking_reference  VARCHAR(6)    NOT NULL UNIQUE,
    passenger_id       BIGINT        NOT NULL REFERENCES passenger(id),
    flight_id          BIGINT        NOT NULL,
    flight_number      VARCHAR(10)   NOT NULL,
    departure_time     TIMESTAMPTZ   NOT NULL,
    gate               VARCHAR(10),
    flight_status      VARCHAR(20),
    seat_number        VARCHAR(5)    NOT NULL,
    price              NUMERIC(10,2) NOT NULL CHECK (price >= 0),
    currency           VARCHAR(3)    NOT NULL DEFAULT 'DKK',
    status             VARCHAR(20)   NOT NULL,
    created_at         TIMESTAMPTZ   NOT NULL DEFAULT now(),
    updated_at         TIMESTAMPTZ   NOT NULL DEFAULT now(),
    CONSTRAINT chk_booking_status CHECK (status IN ('PENDING_PAYMENT','CONFIRMED','CANCELLED','CHECKED_IN'))
);
-- Same seat can only be held by one non-cancelled booking (handles the race condition)
CREATE UNIQUE INDEX ux_booking_active_seat ON booking (flight_id, seat_number) WHERE status <> 'CANCELLED';
CREATE INDEX idx_booking_reference ON booking (booking_reference);
CREATE INDEX idx_booking_passenger ON booking (passenger_id);
CREATE INDEX idx_booking_flight ON booking (flight_id);

-- Idempotency store for consumed events (see messaging package)
CREATE TABLE processed_event (
    event_id      VARCHAR(64)  PRIMARY KEY,
    event_type    VARCHAR(100) NOT NULL,
    processed_at  TIMESTAMPTZ  NOT NULL DEFAULT now()
);
