CREATE TABLE payment (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    booking_reference  VARCHAR(6)    NOT NULL,
    amount             NUMERIC(10,2) NOT NULL CHECK (amount > 0),
    currency           VARCHAR(3)    NOT NULL DEFAULT 'DKK',
    card_last4         VARCHAR(4)    NOT NULL,
    status             VARCHAR(20)   NOT NULL,
    failure_reason     VARCHAR(200),
    created_at         TIMESTAMPTZ   NOT NULL DEFAULT now(),
    updated_at         TIMESTAMPTZ   NOT NULL DEFAULT now(),
    CONSTRAINT chk_payment_status CHECK (status IN ('PENDING','COMPLETED','FAILED','REFUNDED'))
);
CREATE INDEX idx_payment_booking_reference ON payment (booking_reference);

-- Idempotency store for consumed events (see messaging package)
CREATE TABLE processed_event (
    event_id      VARCHAR(64)  PRIMARY KEY,
    event_type    VARCHAR(100) NOT NULL,
    processed_at  TIMESTAMPTZ  NOT NULL DEFAULT now()
);
