CREATE TABLE airline (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    iata_code   VARCHAR(3)   NOT NULL UNIQUE,
    name        VARCHAR(100) NOT NULL,
    country     VARCHAR(100) NOT NULL
);

CREATE TABLE aircraft (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    registration  VARCHAR(20)  NOT NULL UNIQUE,
    model         VARCHAR(100) NOT NULL,
    total_seats   INTEGER      NOT NULL CHECK (total_seats > 0),
    airline_id    BIGINT       NOT NULL REFERENCES airline(id)
);

CREATE TABLE flight (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    flight_number        VARCHAR(10)   NOT NULL,
    airline_id           BIGINT        NOT NULL REFERENCES airline(id),
    aircraft_id          BIGINT        NOT NULL REFERENCES aircraft(id),
    origin               VARCHAR(3)    NOT NULL,
    destination          VARCHAR(3)    NOT NULL,
    scheduled_departure  TIMESTAMPTZ   NOT NULL,
    scheduled_arrival    TIMESTAMPTZ   NOT NULL,
    gate                 VARCHAR(10),
    status               VARCHAR(20)   NOT NULL,
    base_price           NUMERIC(10,2) NOT NULL CHECK (base_price >= 0),
    currency             VARCHAR(3)    NOT NULL DEFAULT 'DKK',
    CONSTRAINT uq_flight_number_departure UNIQUE (flight_number, scheduled_departure),
    CONSTRAINT chk_flight_status CHECK (status IN ('SCHEDULED','BOARDING','DEPARTED','DELAYED','CANCELLED'))
);
CREATE INDEX idx_flight_departure ON flight (scheduled_departure);
CREATE INDEX idx_flight_destination ON flight (destination);

CREATE TABLE seat (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    flight_id     BIGINT      NOT NULL REFERENCES flight(id) ON DELETE CASCADE,
    seat_number   VARCHAR(5)  NOT NULL,
    seat_class    VARCHAR(20) NOT NULL,
    is_available  BOOLEAN     NOT NULL DEFAULT TRUE,
    CONSTRAINT uq_seat_flight_number UNIQUE (flight_id, seat_number),
    CONSTRAINT chk_seat_class CHECK (seat_class IN ('ECONOMY','BUSINESS','FIRST'))
);
CREATE INDEX idx_seat_flight ON seat (flight_id);

-- Idempotency store for consumed events (see messaging package)
CREATE TABLE processed_event (
    event_id      VARCHAR(64)  PRIMARY KEY,
    event_type    VARCHAR(100) NOT NULL,
    processed_at  TIMESTAMPTZ  NOT NULL DEFAULT now()
);
