CREATE TABLE baggage (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tag_number         VARCHAR(12)   NOT NULL UNIQUE,
    booking_reference  VARCHAR(6)    NOT NULL,
    passenger_name     VARCHAR(200)  NOT NULL,
    flight_number      VARCHAR(10)   NOT NULL,
    weight_kg          NUMERIC(5,2)  NOT NULL CHECK (weight_kg > 0),
    type               VARCHAR(20)   NOT NULL,
    status             VARCHAR(20)   NOT NULL,
    last_location      VARCHAR(100),
    created_at         TIMESTAMPTZ   NOT NULL DEFAULT now(),
    updated_at         TIMESTAMPTZ   NOT NULL DEFAULT now(),
    CONSTRAINT chk_baggage_type   CHECK (type IN ('CHECKED','CABIN','SPECIAL')),
    CONSTRAINT chk_baggage_status CHECK (status IN ('REGISTERED','SECURITY','LOADED','IN_TRANSIT','ARRIVED','LOST'))
);
CREATE INDEX idx_baggage_booking_reference ON baggage (booking_reference);
CREATE INDEX idx_baggage_flight_number     ON baggage (flight_number);

-- Local snapshot of bookings, maintained from booking.* events (booking-service is the source of truth)
CREATE TABLE booking_snapshot (
    booking_reference  VARCHAR(6)    PRIMARY KEY,
    passenger_name     VARCHAR(200)  NOT NULL,
    flight_number      VARCHAR(10)   NOT NULL,
    flight_id          BIGINT,
    status             VARCHAR(20)   NOT NULL,
    updated_at         TIMESTAMPTZ   NOT NULL DEFAULT now()
);
CREATE INDEX idx_booking_snapshot_flight_number ON booking_snapshot (flight_number);

-- Idempotency store for consumed events (see messaging package)
CREATE TABLE processed_event (
    event_id      VARCHAR(64)  PRIMARY KEY,
    event_type    VARCHAR(100) NOT NULL,
    processed_at  TIMESTAMPTZ  NOT NULL DEFAULT now()
);
