CREATE TABLE nav_node (
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name      VARCHAR(100) NOT NULL,
    terminal  VARCHAR(5)   NOT NULL,
    floor     INTEGER      NOT NULL DEFAULT 0,
    x         INTEGER      NOT NULL,
    y         INTEGER      NOT NULL,
    type      VARCHAR(20)  NOT NULL,
    CONSTRAINT chk_nav_node_type CHECK (type IN ('SHOP','GATE','SECURITY','ENTRANCE','JUNCTION','ELEVATOR'))
);
CREATE INDEX idx_nav_node_terminal_floor ON nav_node (terminal, floor);

-- Edges are stored ONCE and treated as bidirectional by the routing code.
CREATE TABLE nav_edge (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    from_node_id  BIGINT  NOT NULL REFERENCES nav_node(id) ON DELETE CASCADE,
    to_node_id    BIGINT  NOT NULL REFERENCES nav_node(id) ON DELETE CASCADE,
    distance_m    INTEGER NOT NULL CHECK (distance_m > 0),
    accessible    BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT uq_nav_edge UNIQUE (from_node_id, to_node_id),
    CONSTRAINT chk_nav_edge_not_self CHECK (from_node_id <> to_node_id)
);

CREATE TABLE shop (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name           VARCHAR(100) NOT NULL,
    category       VARCHAR(20)  NOT NULL,
    terminal       VARCHAR(5)   NOT NULL,
    zone           VARCHAR(50)  NOT NULL,
    floor          INTEGER      NOT NULL DEFAULT 0,
    opening_hours  VARCHAR(50)  NOT NULL,
    description    TEXT,
    node_id        BIGINT REFERENCES nav_node(id) ON DELETE SET NULL,
    CONSTRAINT chk_shop_category CHECK (category IN ('FOOD','RETAIL','DUTY_FREE','SERVICE','LOUNGE'))
);
CREATE INDEX idx_shop_terminal ON shop (terminal);
CREATE INDEX idx_shop_category ON shop (category);
CREATE INDEX idx_shop_node ON shop (node_id);

-- Idempotency store for consumed events (see messaging package)
CREATE TABLE processed_event (
    event_id      VARCHAR(64)  PRIMARY KEY,
    event_type    VARCHAR(100) NOT NULL,
    processed_at  TIMESTAMPTZ  NOT NULL DEFAULT now()
);
