-- Transactional outbox: events are written here in the same transaction as the state change
-- and sent to RabbitMQ by OutboxRelay (see messaging package).
CREATE TABLE outbox_event (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id      VARCHAR(64)  NOT NULL UNIQUE,
    event_type    VARCHAR(100) NOT NULL,
    payload       JSONB        NOT NULL,          -- the whole EventEnvelope, exactly as sent on the wire
    created_at    TIMESTAMPTZ  NOT NULL DEFAULT now(),
    published_at  TIMESTAMPTZ,
    attempts      INTEGER      NOT NULL DEFAULT 0,
    last_error    TEXT
);

-- The relay only ever asks for "oldest unpublished rows"; a partial index keeps that cheap
-- no matter how many published rows are retained.
CREATE INDEX idx_outbox_event_pending ON outbox_event (id) WHERE published_at IS NULL;
